#version: '3'
#volumes:
#  postgres_data: {}
#services:
#  app:
#    build:
#      context: .
#      dockerfile: ./docker/app/DockerFile
#    command: rails server -p 3000 -b '0.0.0.0'
#    depends_on:
#      - db
#  db:
#    image: postgres
#    volumes:
#      - postgres_data:/var/lib/postgresql/data
#  web:
#    build:
#      context: .
#      dockerfile: ./docker/web/DockerFile
#    depends_on:
#      - app
#    ports:
#      - "3000:3000"
#
version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/Overtime
    ports:
      - "3000:3000"
    depends_on:
      - db