default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV["POSTGRES_USER"] %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>
  pool: 5
  host: <%= ENV["POSTGRES_HOST"] %>

development:
  <<: *default
  database: overtime_development
test:
  <<: *default
  database: overtime_test

production:
  <<: *default
  database: overtime_production
