default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: postgres
  pool: 5
  host: db

development:
  <<: *default
  database: overtime_development
test:
  <<: *default
  database: overtime_test

production:
  <<: *default
  database: overtime_production
